#library(adventr)
library(aod)
library(apaTables)#https://dstanley4.github.io/apaTables/articles/apaTables.html
library(car)
library(clubSandwich)
library(correlation)
library(data.table)
library("DataCombine")#Used to create leads in data.
library(DiagrammeR)
library(downloader)
library(dplyr)
library(effects)
library(foreign)
library(ggeffects)
library(ggiraphExtra)
library(ggplot2)
library(ggplotAssist)
library(ggstance)
library(gridExtra)
#library(here)
library(Hmisc)
library(huxtable)
library("interactions")#https://www.rdocumentation.org/packages/interactions/versions/1.1.3
library(jtools)
library(knitr)
library(lavaan)
library(lavaanPlot)#https://cran.r-project.org/web/packages/lavaanPlot/vignettes/Intro_to_lavaanPlot.html
library(lm.beta)
library(lme4)
library(lmerTest)
library(lmtest)
library(MASS)
library(Matrix)
library(matrixcalc)
library(mediation)
library(metafor)
library(MplusAutomation)
#https://www.youtube.com/watch?v=Rm77PTrq6VY
#https://www.youtube.com/watch?v=1x3HW1RczAo
#http://www2.uaem.mx/r-mirror/web/packages/MplusAutomation/vignettes/Vignette.pdf
#Full material:https://garberadamc.github.io/project-site/
#https://michaelhallquist.github.io/MplusAutomation/articles/vignette.html
library(msm)
library(multcomp)
library(multilevel)
library(nlme)
library(openxlsx)
library(parameters)
library(plm)
library("panelr")
library(plyr)
library(processR)
library(psych)
library(pastecs)
library("psychmeta")
library("performance")#https://easystats.github.io/performance/index.html
#https://easystats.github.io/performance/reference/test_performance.html
library("readr")
library("readxl")
library(reshape)
library(RSA)
library(rwa)#https://github.com/martinctc/rwa#:~:text=RWA%20decomposes%20the%20total%20variance,of%20the%20various%20predictor%20variables.&text=It%20helps%20to%20answer%20%22which,contribution%20to%20R%2DSquare%22.
library(sandwich)
library(segmented)
library("semPlot")
library(semTable)#https://pj.freefaculty.org/R/semtable.pdf
library(simglm)
#library("sjPlot")
library(surveytoolbox)
library(texreg)
library("tibble")
library(tidySEM)
#library("xlsx")
#library(xlsx)

library(predict3d)
#https://rpubs.com/cardiomoon/474707
#https://rpubs.com/cardiomoon/475466
library(bruceR)